highlighter:      rouge

title:            'Notes and Musings'
description:      'A collection of personal notes and academic school notes.'

author:
  name:           'Giovanni Mostert'

paginate:         5

github:
  repo:           https://github.com/mostertg/mostertg.github.io
  
# Google Analytics
google_analytics: UA-91246521-1
